import type { Metadata } from "next";
import { Geist, Geist_Mono,Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const plusjakartasans = Plus_Jakarta_Sans({
  variable: "--font-geist-jakarta",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${plusjakartasans.variable} ${geistMono.variable} antialiased  w-full min-h-screen`}
      >
      <Navbar />
        {children}
      </body>
    </html>
  );
}
